version: '3.8'

x-blackhole: &blackhole
  build: 
    context: .
    dockerfile: Dockerfile.blackhole
  container_name: blackhole${APPEND}_service
  user: "${PUID:-1000}:${PGID:-1000}"
  volumes:
    - ${BLACKHOLE_RD_MOUNT_TORRENTS_PATH}:${BLACKHOLE_RD_MOUNT_TORRENTS_PATH}
    - ./${BLACKHOLE_BASE_WATCH_PATH}${APPEND}:/app/${BLACKHOLE_BASE_WATCH_PATH}
  env_file:
    - .env
  restart: unless-stopped
  profiles: [blackhole-all, all]

services:
  blackhole:
    <<: *blackhole
  profiles: [blackhole]

  blackhole4k:
    <<: *blackhole
    environment:
      - APPEND=4k
      - SONARR_HOST=${SONARR_HOST_4K}
      - SONARR_API_KEY=${SONARR_API_KEY_4K}
      - RADARR_HOST=${RADARR_HOST_4K}
      - RADARR_API_KEY=${RADARR_API_KEY_4K}
    profiles: [blackhole4k]

  watchlist:
    build: 
      context: .
      dockerfile: Dockerfile.watchlist
    container_name: watchlist_service
    volumes:
      - ./shared/tokens.json:/app/shared/tokens.json
    env_file:
      - .env
    restart: unless-stopped
    profiles: [watchlist, all]

  plex_authentication:
    build: 
      context: .
      dockerfile: Dockerfile.plex_authentication
    container_name: plex_authentication_service
    volumes:
      - ./shared/tokens.json:/app/shared/tokens.json
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - SERVER_DOMAIN=${SERVER_DOMAIN}:8000
    restart: unless-stopped
    profiles: [plex_authentication, all]

  plex_request:
    build: 
      context: .
      dockerfile: Dockerfile.plex_request
    container_name: plex_request_service
    volumes:
      - ./shared/tokens.json:/app/shared/tokens.json
    ports:
      - 8001:8000
    env_file:
      - .env
    restart: unless-stopped
    profiles: [plex_request, all]

