version: '3.8'

x-blackhole: &blackhole
  build: 
    context: .
    dockerfile: Dockerfile.blackhole
  user: "${PUID:-1000}:${PGID:-1000}"
  env_file:
    - .env
  restart: unless-stopped

services:
  blackhole:
    <<: *blackhole
    container_name: blackhole_service
    volumes:
      - ${BLACKHOLE_RD_MOUNT_TORRENTS_PATH}:${BLACKHOLE_RD_MOUNT_TORRENTS_PATH}
      - ./${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}:/app/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}
      - ./${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}:/app/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}
    profiles: [blackhole, blackhole_all, all]

  blackhole4k:
    <<: *blackhole
    container_name: blackhole_4k_service
    environment:
      - SONARR_HOST=${SONARR_HOST_4K}
      - SONARR_API_KEY=${SONARR_API_KEY_4K}
      - RADARR_HOST=${RADARR_HOST_4K}
      - RADARR_API_KEY=${RADARR_API_KEY_4K}
    volumes:
      - ./${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH} 4k:/app/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}
      - ./${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH} 4k:/app/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}
    profiles: [blackhole_4k, blackhole_all, all]

  watchlist:
    build: 
      context: .
      dockerfile: Dockerfile.watchlist
    container_name: watchlist_service
    volumes:
      - ./shared/tokens.json:/app/shared/tokens.json
    env_file:
      - .env
    restart: unless-stopped
    profiles: [watchlist, all]

  plex_authentication:
    build: 
      context: .
      dockerfile: Dockerfile.plex_authentication
    container_name: plex_authentication_service
    volumes:
      - ./shared/tokens.json:/app/shared/tokens.json
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - SERVER_DOMAIN=${SERVER_DOMAIN}:8000
    restart: unless-stopped
    profiles: [plex_authentication, all]

  plex_request:
    build: 
      context: .
      dockerfile: Dockerfile.plex_request
    container_name: plex_request_service
    volumes:
      - ./shared/tokens.json:/app/shared/tokens.json
    ports:
      - 8001:8000
    env_file:
      - .env
    restart: unless-stopped
    profiles: [plex_request, all]

